spring:
  application:
    name: myroutine
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false

management:
  server:
    port: 8081

myroutine:
  business-zone: Asia/Seoul
